/*
 * Copyright 2026 Kingsrook, LLC
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0
 */
package com.kingsrook.qqq.all;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/** Creates the small, repeatable core demo data set before the web server starts. */
final class CoreData
{
   private CoreData()
   {
   }

   static String h2DatabaseName(Path dataDirectory)
   {
      return dataDirectory.resolve("h2/qqq-all").toAbsolutePath().toString();
   }

   static Path sqlitePath(Path dataDirectory)
   {
      return dataDirectory.resolve("sqlite/qqq-all.db");
   }

   static void seed(Path dataDirectory) throws IOException, SQLException
   {
      Files.createDirectories(dataDirectory.resolve("h2"));
      Files.createDirectories(dataDirectory.resolve("sqlite"));
      Files.createDirectories(dataDirectory.resolve("files/products"));

      try(Connection connection = DriverManager.getConnection(
         "jdbc:h2:file:" + h2DatabaseName(dataDirectory) + ";MODE=MySQL;DB_CLOSE_DELAY=-1", "sa", "");
          Statement statement = connection.createStatement())
      {
         statement.execute("CREATE TABLE IF NOT EXISTS customer (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(120), email VARCHAR(200))");
         statement.execute("CREATE TABLE IF NOT EXISTS orders (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_no VARCHAR(40), customer_id INTEGER, status VARCHAR(40))");
         statement.execute("MERGE INTO customer (id, name, email) KEY (id) VALUES (1, 'Ada Lovelace', 'ada@example.test'), (2, 'Grace Hopper', 'grace@example.test')");
         statement.execute("MERGE INTO orders (id, order_no, customer_id, status) KEY (id) VALUES (1, 'ORD-1001', 1, 'NEW')");
      }

      try(Connection connection = DriverManager.getConnection("jdbc:sqlite:" + sqlitePath(dataDirectory));
          Statement statement = connection.createStatement())
      {
         statement.execute("CREATE TABLE IF NOT EXISTS order_line (id INTEGER PRIMARY KEY, order_id INTEGER, product_id INTEGER, quantity INTEGER)");
         statement.execute("INSERT OR IGNORE INTO order_line (id, order_id, product_id, quantity) VALUES (1, 1, 1, 2)");
      }

      Path product = dataDirectory.resolve("files/products/1.json");
      if(Files.notExists(product))
      {
         Files.writeString(product, "{\"id\":1,\"name\":\"QRun Starter Kit\",\"price\":29.00}\n");
      }
   }
}
