/*
 * Copyright 2026 Kingsrook, LLC
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0
 */
package com.kingsrook.qqq.all;

import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import com.kingsrook.qqq.backend.module.rdbms.jdbc.ConnectionManager;
import com.kingsrook.qqq.backend.module.rdbms.model.metadata.RDBMSBackendMetaData;
import com.kingsrook.qqq.backend.core.model.metadata.QInstance;
import com.kingsrook.qqq.backend.core.model.metadata.fields.QFieldMetaData;
import com.kingsrook.qqq.backend.core.model.metadata.fields.QFieldType;
import com.kingsrook.qqq.backend.core.model.metadata.tables.QTableMetaData;
import com.kingsrook.qqq.backend.module.rdbms.model.metadata.RDBMSTableBackendDetails;

/** Creates repeatable local tables for the qbit metadata exposed by core. */
final class DemoQBitData
{
   /** These tables have hand-maintained PostgreSQL DDL in infra/postgres/01 and 02. */
   private static final Set<String> POSTGRES_MANAGED_TABLES = Set.of("warehouse_customer", "user_session",
      "redirect_state", "user", "role", "permission", "role_permission_int", "user_role_int",
      "user_permission_int");

   private DemoQBitData()
   {
   }

   static void ensureSchema(Path dataDirectory, QInstance instance, Integer port) throws SQLException
   {
      try(Connection connection = DriverManager.getConnection(
         "jdbc:h2:file:" + CoreData.h2DatabaseName(dataDirectory) + ";MODE=MySQL;DB_CLOSE_DELAY=-1", "sa", "");
          Statement statement = connection.createStatement())
      {
         for(QTableMetaData table : instance.getTables().values())
         {
            if(!"h2".equals(table.getBackendName()) || "customer".equals(table.getName()) || "order".equals(table.getName()))
            {
               continue;
            }
            String tableName = table.getBackendDetails() instanceof RDBMSTableBackendDetails details
               ? details.getTableName() : table.getName();
            List<String> columns = new ArrayList<>();
            for(QFieldMetaData field : table.getFields().values())
            {
               String name = field.getBackendName() == null ? field.getName() : field.getBackendName();
               String type = sqlType(field.getType());
               String identity = field.getName().equals(table.getPrimaryKeyField())
                  && (field.getType() == QFieldType.INTEGER || field.getType() == QFieldType.LONG)
                  ? " GENERATED BY DEFAULT AS IDENTITY" : "";
               String primaryKey = field.getName().equals(table.getPrimaryKeyField()) ? " PRIMARY KEY" : "";
               columns.add(identifier(name) + " " + type + identity + primaryKey);
            }
            if(!columns.isEmpty())
            {
               statement.execute("CREATE TABLE IF NOT EXISTS " + identifier(tableName)
                  + " (" + String.join(", ", columns) + ")");
            }
         }
         statement.execute("MERGE INTO shipping_country (id, name, alpha2_code) KEY (id) VALUES (1, 'United States', 'US')");
         statement.execute("MERGE INTO shipping_stateProvince (id, name, country_id) KEY (id) VALUES (1, 'Illinois', 1)");
         statement.execute("MERGE INTO shipping_city (id, name, state_province_id, latitude, longitude) KEY (id) "
            + "VALUES (1, 'Chicago', 1, 41.8781, -87.6298)");
         statement.execute("MERGE INTO address (id, customer_id, line1, city_id) KEY (id) "
            + "VALUES (1, 1, '1 Demo Street', 1)");
         statement.execute("MERGE INTO customizable_table (id, table_name, is_active, default_table_view_id) KEY (id) "
            + "VALUES (1, 'customer', true, 1)");
         statement.execute("MERGE INTO table_view (id, customizable_table_id, name) KEY (id) "
            + "VALUES (1, 1, 'Customer Directory')");
         statement.execute("MERGE INTO table_view_field (id, table_view_id, field_name, access_level) KEY (id) VALUES "
            + "(1, 1, 'customer.id', 'READ_ONLY'), "
            + "(2, 1, 'customer.name', 'EDITABLE_OPTIONAL'), "
            + "(3, 1, 'customer.email', 'EDITABLE_OPTIONAL')");
         statement.execute("MERGE INTO workflow (id, name, workflow_type_name, table_name, current_workflow_revision_id) "
            + "KEY (id) VALUES (1, 'Order Status Review', 'RecordWorkflow', 'order', 1)");
         statement.execute("MERGE INTO workflow_revision (id, workflow_id, version_no, start_step_no, commit_message, author) "
            + "KEY (id) VALUES (1, 1, 1, 1, 'Demo order review', 'qqq-all')");
         statement.execute("MERGE INTO workflow_step (id, workflow_revision_id, step_no, workflow_step_type_name, summary, input_values_json) "
            + "KEY (id) VALUES (1, 1, 1, 'updateInputRecordField', 'Mark order reviewed', "
            + "'{\"fieldName\":\"status\",\"value\":\"REVIEWED\"}')");
         statement.execute("MERGE INTO webhook (id, name, url, active_status_id, health_status_id) KEY (id) "
            + "VALUES (1, 'Local Order Receiver', 'http://127.0.0.1:" + port + "/demo/order-webhook', 1, 1)");
         statement.execute("MERGE INTO webhook_subscription (id, webhook_id, webhook_event_type_name, "
            + "active_status_id, api_name, api_version, create_date) KEY (id) "
            + "VALUES (1, 1, 'orderStored', 1, 'none', 'none', CURRENT_TIMESTAMP)");
      }
   }

   static void ensurePostgresSchema(QInstance instance) throws SQLException
   {
      RDBMSBackendMetaData backend = (RDBMSBackendMetaData) instance.getBackend("postgres");
      try(Connection connection = DriverManager.getConnection(ConnectionManager.getJdbcUrl(backend),
         backend.getUsername(), backend.getPassword());
          Statement statement = connection.createStatement())
      {
         for(String sql : postgresSchemaStatements(instance))
         {
            statement.execute(sql);
         }
         for(QTableMetaData table : postgresQBitTables(instance))
         {
            assertPostgresColumns(connection, table);
         }
      }
   }

   static List<String> postgresSchemaStatements(QInstance instance)
   {
      List<String> statements = new ArrayList<>();
      for(QTableMetaData table : postgresQBitTables(instance))
      {
         String tableName = postgresTableName(table);
         List<String> columns = new ArrayList<>();
         for(QFieldMetaData field : table.getFields().values())
         {
            String name = field.getBackendName() == null ? field.getName() : field.getBackendName();
            String identity = field.getName().equals(table.getPrimaryKeyField())
               && (field.getType() == QFieldType.INTEGER || field.getType() == QFieldType.LONG)
               ? " GENERATED BY DEFAULT AS IDENTITY" : "";
            String primaryKey = field.getName().equals(table.getPrimaryKeyField()) ? " PRIMARY KEY" : "";
            columns.add(postgresIdentifier(name) + " " + postgresSqlType(field.getType()) + identity + primaryKey);
         }
         statements.add("CREATE TABLE IF NOT EXISTS " + postgresIdentifier(tableName)
            + " (" + String.join(", ", columns) + ")");
      }
      return statements;
   }

   private static List<QTableMetaData> postgresQBitTables(QInstance instance)
   {
      return instance.getTables().values().stream()
         .filter(table -> "postgres".equals(table.getBackendName()) && !table.getFields().isEmpty())
         .filter(table -> !POSTGRES_MANAGED_TABLES.contains(postgresTableName(table)))
         .toList();
   }

   private static String postgresTableName(QTableMetaData table)
   {
      return table.getBackendDetails() instanceof RDBMSTableBackendDetails details
         ? details.getTableName() : table.getName();
   }

   private static void assertPostgresColumns(Connection connection, QTableMetaData table) throws SQLException
   {
      String tableName = postgresTableName(table);
      Map<String, String> actual = new HashMap<>();
      try(PreparedStatement query = connection.prepareStatement("SELECT column_name, data_type "
         + "FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = ?"))
      {
         query.setString(1, tableName);
         try(ResultSet rows = query.executeQuery())
         {
            while(rows.next())
            {
               actual.put(rows.getString(1), rows.getString(2));
            }
         }
      }
      for(QFieldMetaData field : table.getFields().values())
      {
         String columnName = field.getBackendName() == null ? field.getName() : field.getBackendName();
         String expectedType = postgresInformationSchemaType(field.getType());
         String actualType = actual.get(columnName);
         if(!expectedType.equals(actualType))
         {
            throw new SQLException("Full-profile table " + tableName + " column " + columnName
               + " must be " + expectedType + "; found " + (actualType == null ? "missing" : actualType)
               + ". Recreate the demo volume or migrate the persisted schema.");
         }
      }
   }

   private static String postgresInformationSchemaType(QFieldType type)
   {
      return switch(type)
      {
         case INTEGER -> "integer";
         case LONG -> "bigint";
         case DECIMAL -> "numeric";
         case BOOLEAN -> "boolean";
         case DATE -> "date";
         case TIME -> "time without time zone";
         case DATE_TIME -> "timestamp without time zone";
         case BLOB -> "bytea";
         case STRING, PASSWORD -> "character varying";
         case TEXT, HTML -> "text";
      };
   }

   private static String postgresIdentifier(String value)
   {
      if(value == null || !value.matches("[A-Za-z][A-Za-z0-9_]*"))
      {
         throw new IllegalArgumentException("Unsupported demo schema identifier");
      }
      return "\"" + value + "\"";
   }

   private static String postgresSqlType(QFieldType type)
   {
      return switch(type)
      {
         case INTEGER -> "INTEGER";
         case LONG -> "BIGINT";
         case DECIMAL -> "DECIMAL(20,6)";
         case BOOLEAN -> "BOOLEAN";
         case DATE -> "DATE";
         case TIME -> "TIME";
         case DATE_TIME -> "TIMESTAMP";
         case BLOB -> "BYTEA";
         case STRING, PASSWORD -> "VARCHAR(4000)";
         case TEXT, HTML -> "TEXT";
      };
   }

   private static String identifier(String value)
   {
      if(value == null || !value.matches("[A-Za-z][A-Za-z0-9_]*"))
      {
         throw new IllegalArgumentException("Unsupported demo schema identifier");
      }
      if("value".equalsIgnoreCase(value) || "key".equalsIgnoreCase(value))
      {
         return "`" + value + "`";
      }
      return value;
   }

   private static String sqlType(QFieldType type)
   {
      return switch(type)
      {
         case INTEGER -> "INTEGER";
         case LONG -> "BIGINT";
         case DECIMAL -> "DECIMAL(20,6)";
         case BOOLEAN -> "BOOLEAN";
         case DATE -> "DATE";
         case TIME -> "TIME";
         case DATE_TIME -> "TIMESTAMP";
         case BLOB -> "BLOB";
         case STRING, PASSWORD -> "VARCHAR(4000)";
         case TEXT, HTML -> "CLOB";
      };
   }
}
