CREATE TABLE IF NOT EXISTS warehouse_customer (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(120) NOT NULL
);

INSERT INTO warehouse_customer (id, name) VALUES (1, 'Demo Warehouse Customer')
ON CONFLICT (id) DO NOTHING;
