services:
  app-full:
    environment:
      QQQ_ALL_OPENSEARCH_HOST: opensearch
  opensearch:
    ports: !override
      - "127.0.0.1::9200"
  rabbitmq:
    ports: !override
      - "127.0.0.1::15672"
  artemis:
    ports: !override
      - "127.0.0.1::8161"
  mailpit:
    ports: !override
      - "127.0.0.1::8025"
  minio:
    ports: !override
      - "127.0.0.1::9001"
